#pragma once
class Polycrystalline3;
class Crystallite3;
class Simplex3;
class FrontFacet3;
class ShellFacet3;
class Facet3;
class FrontEdge3;
class ShellEdge3;
class Edge3;
class Vertex3;
class ShellVertex3;
class Vector3;